### ISSUE TITLE
Failed to sign apk: Malformed ZIP entry: <Some File>

### ISSUE THREAD

**Issue by bmax121** [LSPosed/LSPatch#12]
signApkUsingAndroidApksigner 函数签名失败，报错如题，
把未签名的 apk 解压后重新压缩，然后用 apksigner 签名就正常了

**Comment by bmax121** [comment]
好像跟 zipalign 有关，没深究原因

**Comment by 327135569** [comment]
最近这块有一些提交, PULL最新的代码试试?
