### ISSUE TITLE
[Bug] 闪退

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/LSPatch#120]
### Steps to reproduce/复现步骤

ci版本340以上都会闪退

### Expected behaviour/预期行为

正常启动

### Actual behaviour/实际行为

闪退

### Xposed Module List/Xposed 模块列表

```Shell
io.github.qauxv
```

### LSPatch version/LSPatch 版本

0.4（345）

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

12.14.0

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

10-21 22:39:05.046  6367  6367 I com.tencent.tim: Late-enabling -Xcheck:jni
10-21 22:39:05.075  6367  6367 D ActivityThread: setConscryptValidator
10-21 22:39:05.075  6367  6367 D ActivityThread: setConscryptValidator - put
10-21 22:39:05.101  6367  6367 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10353; state: DISABLED
10-21 22:39:05.106  6367  6367 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
10-21 22:39:05.115  6367  6367 W com.tencent.tim: Accessing hidden method Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime; (unsupported,core-platform-api, reflection, allowed)
10-21 22:39:05.115  6367  6367 W com.tencent.tim: Accessing hidden method Ldalvik/system/VMRuntime;->vmInstructionSet()Ljava/lang/String; (unsupported,core-platform-api, reflection, allowed)
10-21 22:39:05.119  6367  6367 I LSPatch-MetaLoader: Bootstrap loader from manager
10-21 22:39:05.119  6367  6367 W com.tencent.tim: Accessing hidden method Landroid/content/pm/IPackageManager;->getApplicationInfo(Ljava/lang/String;JI)Landroid/content/pm/ApplicationInfo; (blocked, linking, denied)
10-21 22:39:05.119  6367  6367 D AndroidRuntime: Shutting down VM
10-21 22:39:05.119  6367  6367 E AndroidRuntime: FATAL EXCEPTION: main
10-21 22:39:05.119  6367  6367 E AndroidRuntime: Process: com.tencent.tim, PID: 6367
10-21 22:39:05.119  6367  6367 E AndroidRuntime: java.lang.ExceptionInInitializerError
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(LSPAppComponentFactoryStub.java:94)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.LoadedApk.createAppFactory(LoadedApk.java:289)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1064)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1151)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.LoadedApk.getResources(LoadedApk.java:1475)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:3264)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:3256)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7461)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8741)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
10-21 22:39:05.119  6367  6367 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;JI)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(LSPAppComponentFactoryStub.java:71)
10-21 22:39:05.119  6367  6367 E AndroidRuntime:        ... 17 more
10-21 22:39:05.153  6367  6367 I Process : Sending signal. PID: 6367 SIG: 9

**Comment by yujincheng08** [comment]
0bc6407caffbf8bef54af7b62ea1ab975370c9cd

**Comment by Dr-TSNG** [comment]
0bc6407caffbf8bef54af7b62ea1ab975370c9cd
