### ISSUE TITLE
[Feature Request] 嵌入模块时可选择安装包（而不是只能选择已安装的模块）

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#122]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

嵌入模块时只能选择本机上已安装的模块

### Describe the solution you'd like/描述你想要的解决方案

也可以选择一个模块的安装包（而不用预先安装它）

**Comment by yujincheng08** [comment]
#225
