### ISSUE TITLE
[Feature Request] 增加使用shizuku读取应用列表的可选项

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#123]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

在OPPO Watch 3中禁止应用读取应用列表，同时在一些定制ROM中可能也存在不开放应用列表权限或应用列表不全的情况

### Describe the solution you'd like/描述你想要的解决方案

希望在设置中增加『使用shizuku读取应用列表』的可选项及对应功能

**Comment by vvb2060** [comment]
https://developer.android.com/training/package-visibility

**Comment by jiwangyihao** [comment]
> https://developer.android.com/training/package-visibility

虽然但是，当然是用了各种方法都拿不到权限才会提这个issue啊😂

**Comment by vvb2060** [comment]
我们申请有该权限，因此无法获取应用列表表明你的系统存在问题，建议使用符合 Android 兼容性定义文档的系统

**Comment by jiwangyihao** [comment]
> 我们申请有该权限，因此无法获取应用列表表明你的系统存在问题，建议使用符合 Android 兼容性定义文档的系统

我知道是系统有问题😂
问题是我换不了啊😂
其实只是想问问看能不能行来着，给你们添麻烦了😁

**Comment by jiwangyihao** [comment]
> 我们申请有该权限，因此无法获取应用列表表明你的系统存在问题，建议使用符合 Android 兼容性定义文档的系统

那个，我想请教您一个问题：

现在在使用 LSPatch 的便携模式嵌入像 APP Settings 这样的需要在外部应用中进行配置的模块时似乎是没有办法进行配置的。（而我现在用本地模式的话 LSPatch 又读不到应用列表）所以我就想能不能手工为它添加配置。

我简单读了一下 APP Settings 的源码，发现它的配置似乎放在了 XSharedPreference 里面（如果不对烦请指正），所以我就想请教下它在文件系统中的路径是什么，有没有手工编辑的可能。

另外，如果您知道的话：
- 还有其他可以更改应用 DPI 的模块吗？
- 还有其他更改单个应用 DPI 的方案吗？（APP Cloner 除外）
- xp 模块更改应用 DPI 的原理是什么？

不胜感激！
