### ISSUE TITLE
希望支持对split apk文件的修补

### ISSUE THREAD

**Issue by DRAWCORE** [LSPosed/LSPatch#126]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

希望可以支持对split安装包的修补

### Describe the solution you'd like/描述你想要的解决方案

.

**Comment by Dr-TSNG** [comment]
有没有一种可能本来就支持

**Comment by DRAWCORE** [comment]
在选择文件进行修补的时候，只能选择.apk格式的安装包，不能选择.apks的split apk文件呀，那么如何选择split安装包进行修补呢，不是从已安装的程序中。

**Comment by Dr-TSNG** [comment]
1. apks 不是官方格式
2. apk 可以多选

**Comment by DRAWCORE** [comment]
那就是说，把一个split apk进行解压得到多个apk文件，然后选择这些全部apk文件进行修补呗，那么输出的是什么文件呢
