### ISSUE TITLE
[Feature Request] 使用便捷模式之后希望可访问resource资源

### ISSUE THREAD

**Issue by microCloudCode** [LSPosed/LSPatch#131]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

目前使用便捷模式之后不知道如何访问模块内的resource资源，请问有合适的方案吗？找了好久

### Describe the solution you'd like/描述你想要的解决方案

如何访问？

**Comment by yujincheng08** [comment]
https://api.xposed.info/reference/android/content/res/XModuleResources.html
