### ISSUE TITLE
[Feature Request] 在未连接『Shizuku』时调用系统包管理器安装应用

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#132]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

现在在未连接『Shizuku』时修补应用以后只能用文件管理器打开对应文件夹手动安装，很不方便

### Describe the solution you'd like/描述你想要的解决方案

希望可以在未连接『Shizuku』时调用系统包管理器安装应用

**Comment by vvb2060** [comment]
小米屏蔽了系统安装器
