### ISSUE TITLE
[Bug] 修补 NP 管理器时提示『Failed to parse AndroidManifest.xml』

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#135]
### Steps to reproduce/复现步骤

1. 下载 NP 管理器：https://wwk.lanzoue.com/iSLE70fd346h
2. 修补它
3. 报错

### Expected behaviour/预期行为

正常修补

### Actual behaviour/实际行为

修补失败

### Xposed Module List/Xposed 模块列表

```Shell
无
```

### LSPatch version/LSPatch 版本

v0.5.1-360

### Android version/Android 版本

jar

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Processing C:\Users\34404\Desktop\NP.apk -> C:\Users\34404\Desktop\.\NP-360-lspatched.apk
apk path: C:\Users\34404\Desktop\NP.apk
Parsing original apk...
Register apk signer with default keystore...
Original signature
3082034b30820233a00302010202044a138539300d06092a864886f70d01010b05003055310b3009060355040613026a73310b3009060355040813026d74310b3009060355040713026d74310b3009060355040a13026d74310b3009060355040b13026d743112301006035504031309636875696e697565723020170d3139303832323034353632325a180f32313139303732393034353632325a3055310b3009060355040613026a73310b3009060355040813026d74310b3009060355040713026d74310b3009060355040a13026d74310b3009060355040b13026d743112301006035504031309636875696e6975657230820122300d06092a864886f70d01010105000382010f003082010a02820101008729dfe9b8a9e3daa07982fe98ba94a3c9cc1a9d01db59f0f8c20ba2fb42e86663d4035772ee23713ea80e363b03172dbe11305d735f72911d3a98daa74ef8e61ac7a20f5f0650adce21665d40f9221979e0ecde36e8f587cbdb8349f99fa07c492abb577b3139090777ed0710f8794570373c28653409dc5098230131c65a0fa39d8ec9c57c6bfd8b3998a18e0d4bee23a841e701ce00c2d39ead66a096ecf041d8a929ad68c606981ec26d9468dd90a7e8c3dec201819534f8d8b21437cf4f4f38e3bd68cc864c966e75f81776a3bf22c2171eddf0813c6f7e57cf2b8102f9e65108111cfffa5b4eb024c9fdc280b21d287faacea3954538e058f1239664830203010001a321301f301d0603551d0e04160414836c89a114a52834bef1cdb0719eb96e4c302822300d06092a864886f70d01010b050003820101006e3bbab26faf5f6e0f12e4143efe7094ea2b88cf6756754cc09a378eeede9da002625287e35bd1564f4cabaa50c24c8d8314b85bc94988bad6f26871b980f1e069753cf1aa27270b78e61937dbc7bc11874733d0f4299e2824c7c689ab8d26b9ee22a42f25806c9e7daa2a11573cf67e508339bbb6cf1f5bce4d4511f85f64737db0f2b758c20ea30ade26e035cbb873fd554ba15d307492af5e012fe314cb72ad4db56957d3fc2285cc5b08882e1dbee7a82a6d2ff4bd9b15284491f86081e02449346859c14f39ddef6d3c2ea68dc64a3ec9fea02663453eeb99cf7142c5161a18ba53d70ae449095d816a5a154de6b5c17b9aecc22876555fcfa21fa96ee9
org.lsposed.patch.LSPatch$PatchError: Failed to parse AndroidManifest.xml
        at org.lsposed.patch.LSPatch.patch(LSPatch.java:223)
        at org.lsposed.patch.LSPatch.doCommandLine(LSPatch.java:165)
        at org.lsposed.patch.LSPatch.main(LSPatch.java:140)

**Comment by Dr-TSNG** [comment]
c41be02511fd4db6b4d5f47c7f616352bfd128a7

**Comment by Stanyer** [comment]
How could I do when I encounter.the same bug？

**Comment by wayne3602** [comment]
I think it may be the problem of np, it is a troublesome app because it has too much detection.
