### ISSUE TITLE
[Bug] 为『便携模式』应用更新加载器时内嵌的模块被清除

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#136]
### Steps to reproduce/复现步骤

1. 用任意旧版本（如357）修补任意应用并嵌入任意模块
2. 用0.5.1-360更新加载器

### Expected behaviour/预期行为

加载器被更新，模块正常使用

### Actual behaviour/实际行为

加载器被更新，模块被清除

### Xposed Module List/Xposed 模块列表

```Shell
https://github.com/jiwangyihao/app_config
（其他的应该也可以）
```

### LSPatch version/LSPatch 版本

0.5.1-360

### Android version/Android 版本

11

### Shizuku version/Shizuku 版本

v12.12.1

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

此问题似乎不需要日志😂
不方便抓日志，麻烦开发组尝试复现一下吧（要不能复现我再想办法抓日志吧）

**Comment by Dr-TSNG** [comment]
2ace2660b4b8dcb349d5edcba251dab912f4ce6a
