### ISSUE TITLE
[Bug] 『Shizuku』激活了，用框架修补完点安装一直转圈，还有更新驱动器也是一直转圈，文件管理器里能找到修补完的app

### ISSUE THREAD

**Issue by sankuaishitou008** [LSPosed/LSPatch#138]
### Steps to reproduce/复现步骤

『Shizuku』激活了，用框架修补完点安装一直转圈，还有更新驱动器也是一直转圈；
这个问题100%复现

### Expected behaviour/预期行为

正常情况不是应该修补完点安装会直接安装

### Actual behaviour/实际行为

一直转圈不安装修补完的app

### Xposed Module List/Xposed 模块列表

```Shell
微x等模块
```

### LSPatch version/LSPatch 版本

lspatch

### Android version/Android 版本

安卓11

### Shizuku version/Shizuku 版本

A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

没找到

**Comment by yujincheng08** [comment]
没日志。
