### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ahov12345** [LSPosed/LSPatch#141]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

因为一些原因无法调用系统文件管理器

### Describe the solution you'd like/描述你想要的解决方案

支持调用第三方文件管理器

**Comment by vvb2060** [comment]
CTS 要求 com.google.android.documentsui 或 com.android.documentsui 必须存在，或者有相同行为的其它应用
