### ISSUE TITLE
希望加入隐藏后台开关

### ISSUE THREAD

**Issue by Mubai-meng** [LSPosed/LSPatch#142]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

如果多任务后台不隐藏的话，多任务后台的一键清理把软件清掉后会影响短暂影响模块的使用（因为即使软件自启动开启和后台无限制等已开启，但清掉后台后自启还需要一定的时间）

### Describe the solution you'd like/描述你想要的解决方案

上次已经加入前台保活的开关，如果再加入后台隐藏的开关我相信软件的使用会更加的完美完善。

**Comment by vvb2060** [comment]
被拉起后本来就不在最近任务

**Comment by Mubai-meng** [comment]
> 被拉起后本来就不在最近任务

是的，但拉起需要一定的时间，这期间模块功能会失效（虽然很短，但还是希望加入这个功能就完美了）

**Comment by vvb2060** [comment]
就算没有后台卡片，没锁定的话一键清理一样杀。加入这个功能不能解决拉起慢的问题

**Comment by Mubai-meng** [comment]
> 就算没有后台卡片，没锁定的话一键清理一样杀。加入这个功能不能解决拉起慢的问题

如果加锁后在隐藏岂不是更好，希望您在考虑一下😂
