### ISSUE TITLE
[Bug] Facebook Messenger Pro

### ISSUE THREAD

**Issue by bthedorff** [LSPosed/LSPatch#143]
### Steps to reproduce/复现步骤

1. Uninstall Facebook Messenger
2. Install version from the Github
3. Try to patch and install Facebook Messenger 

### Expected behaviour/预期行为

Patches and installs

### Actual behaviour/实际行为

Fails to install

### Xposed Module List/Xposed 模块列表

```Shell
LSPatcher
Messenger Pro apk (https://github.com/Mino260806/MessengerPro)
```

### LSPatch version/LSPatch 版本

0.5.1(361)

### Android version/Android 版本

12

### Shizuku version/Shizuku 版本

12.14.0r914.e88de6a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.facebook.orca attempting to redeclare permission com.facebook.receiver.permission.ACCESS already owned by com.facebook.katana

**Comment by vvb2060** [comment]
expected behavior
