### ISSUE TITLE
[Bug] 分身应用闪退

### ISSUE THREAD

**Issue by jinjinjijiao** [LSPosed/LSPatch#144]
### Steps to reproduce/复现步骤

1. 点击分身应用QQ（华为自带应用分身）后闪退
0.5(353)版本后都会闪退

### Expected behaviour/预期行为

正常启动

### Actual behaviour/实际行为

闪退

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### LSPatch version/LSPatch 版本

0.5.1 (361)

### Android version/Android 版本

hm3 (12)

### Shizuku version/Shizuku 版本

12.14.0.r914.e88de6a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: FATAL EXCEPTION: main
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: Process: com.tencent.mobileqq, PID: 29720
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: java.lang.ExceptionInInitializerError
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:420)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.LoadedApk.createAppFactory(LoadedApk.java:280)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1131)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1218)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.LoadedApk.getResources(LoadedApk.java:1504)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3230)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:3213)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8066)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ActivityThread.access$2700(ActivityThread.java:298)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2738)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:117)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:293)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9551)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: Caused by: android.os.RemoteException: Failed to get manager binder
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at org.lsposed.lspatch.service.RemoteApplicationService.<init>(RemoteApplicationService.java:80)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at org.lsposed.lspatch.loader.LSPApplication.onLoad(LSPApplication.java:82)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.Runtime.nativeLoad(Native Method)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.Runtime.nativeLoad(Runtime.java:1121)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:927)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at java.lang.System.load(System.java:1621)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:370)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	... 17 more
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: Caused by: java.util.concurrent.TimeoutException: Bind service timeout
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	at org.lsposed.lspatch.service.RemoteApplicationService.<init>(RemoteApplicationService.java:77)
11-19 20:12:52.997 12810333 29720 29720 E AndroidRuntime: 	... 23 more

**Comment by yujincheng08** [comment]
把 LSPatch 也分身试试？

**Comment by zuowangzuowang** [comment]
我的也是闪退

**Comment by jinjinjijiao** [comment]
> 把 LSPatch 也分身试试？

华为只能分身微信/QQ🤨
