### ISSUE TITLE
[Feature Request] 后台隐藏

### ISSUE THREAD

**Issue by block13566** [LSPosed/LSPatch#149]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

作为一个强迫症，我是很难忍受一个APP挂在后台或者通知栏一个常驻消息的

### Describe the solution you'd like/描述你想要的解决方案

我希望可以有一个太极那样的，只要用返回键退出那么软件后台会被隐藏，这样也不需要用一个常驻消息来保持运行了

**Comment by yujincheng08** [comment]
> 后台会被隐藏，这样也不需要用一个常驻消息来保持运行了

没用。
