### ISSUE TITLE
[Bug] QQ新版apk修补出错

### ISSUE THREAD

**Issue by y3341742136** [LSPosed/LSPatch#152]
### Steps to reproduce/复现步骤

选择com.tencent.mobileqq-8.9.25-3640-3834.apk
添加QAuxiliary模块
本地模式修补

### Expected behaviour/预期行为

正常应该是直接成功然后有安装按钮的

### Actual behaviour/实际行为

实际出现错误

### Xposed Module List/Xposed 模块列表

```Shell
QAuxiliary
```

### LSPatch version/LSPatch 版本

0.5.1（362）

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

12.14.0.r914.e88de6a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64-362-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64.apk
, Parsing original apk...
, Register apk signer with default keystore...
, Original signature
30820253308201bca00302010202044bbb0361300d06092a864886f70d0101050500306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b30090603550403130251513020170d3130303430363039343831375a180f32323834303132303039343831375a306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b300906035504031302515130819f300d06092a864886f70d010101050003818d0030818902818100a15e9756216f694c5915e0b529095254367c4e64faeff07ae13488d946615a58ddc31a415f717d019edc6d30b9603d3e2a7b3de0ab7e0cf52dfee39373bc472fa997027d798d59f81d525a69ecf156e885fd1e2790924386b2230cc90e3b7adc95603ddcf4c40bdc72f22db0f216a99c371d3bf89cba6578c60699e8a0d536950203010001300d06092a864886f70d01010505000381810094a9b80e80691645dd42d6611775a855f71bcd4d77cb60a8e29404035a5e00b21bcc5d4a562482126bd91b6b0e50709377ceb9ef8c2efd12cc8b16afd9a159f350bb270b14204ff065d843832720702e28b41491fbc3a205f5f2f42526d67f17614d8a974de6487b2c866efede3b4e49a0f916baa3c1336fd2ee1b1629652049
, original appComponentFactory class: androidx.core.app.CoreComponentFactory
, Patching apk...
, Adding config...
, Adding metaloader dex...
, Adding loader dex...
, Adding native lib...
, added assets/lspatch/so/x86_64/liblspatch.so
, added assets/lspatch/so/x86/liblspatch.so
, added assets/lspatch/so/armeabi-v7a/liblspatch.so
, added assets/lspatch/so/arm64-v8a/liblspatch.so
, Embedding modules...
,   - io.github.qauxv
, Creating nested apk link...
, Writing apk...
, /data/user/0/org.lsposed.lspatch/cache/tempdir_2294739437204661460/temp_6011241502040241908.data: open failed: ENOENT (No such file or directory)
, java.io.FileNotFoundException: /data/user/0/org.lsposed.lspatch/cache/tempdir_2294739437204661460/temp_6011241502040241908.data: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at c6.f.j(Unknown Source:26)
	at a5.b.j(Unknown Source:4)
	at v4.k.j(Unknown Source:34)
	at c6.q.a(Unknown Source:19)
	at c6.q.<init>(Unknown Source:8)
	at c6.f.j(Unknown Source:16)
	at a5.b.j(Unknown Source:4)
	at y4.y.S(Unknown Source:713)
	at y4.y.close(Unknown Source:4)
	at h9.a.a(Unknown Source:1008)
	at o8.b.j(Unknown Source:23)
	at l7.a.m(Unknown Source:5)
	at a8.d0.run(Unknown Source:105)
	at f8.e.run(Unknown Source:11)
	at g8.i.run(Unknown Source:2)
	at g8.a.run(Unknown Source:79)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8234)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 17 more

**Comment by y3341742136** [comment]
这个试过好几次了第一次出错后第二次直接不能修补会提示错误🤣

**Comment by y3341742136** [comment]
QQ又更新了10005版也是失败这是日志Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64-362-lspatched.apk
, apk path: /data/user/0/org.lsposed.lspatch/cache/apk/Android_8.9.25.10005_537145595_64.apk
, Parsing original apk...
, Register apk signer with default keystore...
, get original signature failed
, g7.c: get original signature failed
	at h9.a.a(Unknown Source:1141)
	at o8.b.j(Unknown Source:23)
	at l7.a.m(Unknown Source:5)
	at a8.d0.run(Unknown Source:105)
	at f8.e.run(Unknown Source:11)
	at g8.i.run(Unknown Source:2)
	at g8.a.run(Unknown Source:79)

**Comment by jiwangyihao** [comment]
第二次提示什么错误，另外试过jar包吗？

**Comment by y3341742136** [comment]
jar包我不知道怎么用🤣

**Comment by jiwangyihao** [comment]
新版失败貌似是因为不支持V3签名

**Comment by jiwangyihao** [comment]
原来那个第二次提示什么错误

**Comment by y3341742136** [comment]
那麻烦修复一下🤣🤣🤣

**Comment by y3341742136** [comment]
稍等一下我给你日志🤣

**Comment by jiwangyihao** [comment]
我不是维护者😂他们好像有一段时间没在这个项目更新了，可能在忙别的
（上一次提交还是合并别人的PR好像）
另外V3签名这个问题8月份就有人提过issue了https://github.com/LSPosed/LSPatch/issues/97
有在逐步解决应该，慢慢等吧

**Comment by y3341742136** [comment]
好像又不出现错误了很迷

**Comment by y3341742136** [comment]
好吧

**Comment by y3341742136** [comment]
反正这个目前还是修补失败错误代码一样

**Comment by yujincheng08** [comment]
无法复现。

**Comment by y3341742136** [comment]
> 无法复现。

真奇怪我这边确实无法修补QQ并且莫名其妙所有版本都不可用了我这是遇到了什么bug？

**Comment by y3341742136** [comment]
Launch patch
, Processing /data/app/~~hCjEJjm79tR4ygJagSnL5A==/com.tencent.mobileqq-HoVycbZwEMsz1XnBcK8n7g==/base.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/base-363-lspatched.apk
, apk path: /data/app/~~hCjEJjm79tR4ygJagSnL5A==/com.tencent.mobileqq-HoVycbZwEMsz1XnBcK8n7g==/base.apk
, Parsing original apk...
, Failed to read zip file '/data/app/~~hCjEJjm79tR4ygJagSnL5A==/com.tencent.mobileqq-HoVycbZwEMsz1XnBcK8n7g==/base.apk'.
, java.io.IOException: Failed to read zip file '/data/app/~~hCjEJjm79tR4ygJagSnL5A==/com.tencent.mobileqq-HoVycbZwEMsz1XnBcK8n7g==/base.apk'.
	at y4.y.<init>(Unknown Source:230)
	at y4.t.<init>(Unknown Source:6)
	at h9.a.a(Unknown Source:327)
	at o8.b.j(Unknown Source:23)
	at l7.a.m(Unknown Source:5)
	at a8.d0.run(Unknown Source:105)
	at f8.e.run(Unknown Source:11)
	at g8.i.run(Unknown Source:2)
	at g8.a.run(Unknown Source:79)
Caused by: java.io.IOException: Cannot read entry 'assets/lspatch/origin.apk' (offset: 769, size: 325310485) because it overlaps with 'assets/appid.ini' (offset: 2532674, size: 139)
	at y4.y.P(Unknown Source:885)
	at y4.y.<init>(Unknown Source:161)
	... 8 more

**Comment by y3341742136** [comment]
不选QQapk直接选已安装的QQ会提示这个错误代码🤣

**Comment by yujincheng08** [comment]
因为你在重复打包啊

**Comment by jiwangyihao** [comment]
重装之后重试吧

**Comment by jiwangyihao** [comment]
用选取安装包那个

**Comment by y3341742136** [comment]
重装QQ吗？

**Comment by y3341742136** [comment]
选取安装包还是会提示那个问题

**Comment by jiwangyihao** [comment]
/data/user/0/org.lsposed.lspatch/cache/tempdir_2294739437204661460/temp_6011241502040241908.data: open failed: ENOENT (No such file or directory)

类似这样的报错我确实也遇到过，似乎出现概率与设备性能成反比（就是在卡的时候更容易出现）

我在手表上遇见过，一般多重试几次就能成功了

**Comment by jiwangyihao** [comment]
重装管理器

**Comment by y3341742136** [comment]
管理器已经重装过好几次了🤣真搞不懂了

**Comment by y3341742136** [comment]
Launch patch
, Processing /data/user/0/org.lsposed.lspatch/cache/apk/com.tencent.mobileqq-8.9.25-3640-3834.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/com.tencent.mobileqq-8.9.25-3640-3834-363-lspatched.apk
, The source apk file does not exit. Please provide a correct path.
, g7.c: The source apk file does not exit. Please provide a correct path.
	at h9.a.a(Unknown Source:1204)
	at o8.b.j(Unknown Source:23)
	at l7.a.m(Unknown Source:5)
	at a8.d0.run(Unknown Source:105)
	at f8.e.run(Unknown Source:11)
	at g8.i.run(Unknown Source:2)
	at g8.a.run(Unknown Source:79)新错误

**Comment by jiwangyihao** [comment]
反正就是管理器有的时候会莫名其妙找不到缓存目录下修补好的文件，但是很难稳定复现，我只确定在卡的时候会概率更高（因为有和我一样的手表用户遇到过类似问题）

**Comment by jiwangyihao** [comment]
你这更离谱了

**Comment by y3341742136** [comment]
又试了几次继续提示ENOENT

**Comment by jiwangyihao** [comment]
啥牌手机

**Comment by y3341742136** [comment]
我就搞不懂了这什么奇葩问题🤣

**Comment by y3341742136** [comment]
OPPO的findx5p天玑版

**Comment by y3341742136** [comment]
colorOS13 C.18内测版（

**Comment by y3341742136** [comment]
明明之前没问题的就修补过几次就给我整这一出（
