### ISSUE TITLE
[Bug] App "com.miraeasset.global" crashes with LSPatch

### ISSUE THREAD

**Issue by akhilkedia** [LSPosed/LSPatch#154]
### Steps to reproduce/复现步骤

1. Install latest LSPatch Debug from [github actions](https://github.com/LSPosed/LSPatch/actions/runs/3729882158)
1. Download the app  [com.miraeasset.global](https://play.google.com/store/apps/details?id=com.miraeasset.global)
1. Patch using LSPatch
1. Open the installed app. The app freezes and finally crashes

This is a banking app, I think some extra "security" features of the app are causing issues, by detecting that it is a modified apk.

### Expected behaviour/预期行为

The app runs

### Actual behaviour/实际行为

The app freezes on open at a blank screen and crashes

### Xposed Module List/Xposed 模块列表

```Shell
Modules enabled - None
Module installed but not enabled in module scope - [AllTrans](https://github.com/akhilkedia/AllTrans) (a non-public build)
```

### LSPatch version/LSPatch 版本

LSPatch version - 0.5.1 (363), Framework Version - 1.8.5 (6649)

### Android version/Android 版本

11 (API 30) Samsung

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I have uploaded a logcat between me opening the app, and when the app first exits - 
https://gist.github.com/akhilkedia/7fef280c63485648ace23269f3e93810

**Comment by akhilkedia** [comment]
Please let me know if you would like me to provide any other details/logs!

**Comment by yujincheng08** [comment]
`12-28 22:56:35.950 20908 20908 I raeasset.globa: System.exit called, status: 0`

it exists itself.
