### ISSUE TITLE
Some files are duplicated

### ISSUE THREAD

**Issue by moeshin** [LSPosed/LSPatch#16]
Like `*.so` file exists in both apk and `orign_apk.bin`.

**Comment by Dr-TSNG** [comment]
Those domplicated files are necessary. However, in the future we will use some zip magic to make them only occupying one portion of storage space.

**Comment by moeshin** [comment]
现在安装包太胖了，求减肥 :joy:

**Comment by moeshin** [comment]
> Those domplicated files are necessary. However, in the future we will use some zip magic to make them only occupying one portion of storage space.

Save the necessary files as a list, and then export orign_apk.bin with the list when the app starts?

**Comment by yujincheng08** [comment]
you don't have permission to manually extract files.

**Comment by moeshin** [comment]
> you don't have permission to manually extract files.

https://github.com/LSPosed/LSPatch/blob/258e10337df2a23701e2e4bd30f68a9f01538908/appstub/src/main/java/org/lsposed/lspatch/appstub/LSPAppComponentFactoryStub.java#L40-L48

no permission?

**Comment by yujincheng08** [comment]
no. you cannot dlopen from there.

**Comment by yujincheng08** [comment]
Fixed by b44b06f, 8c0fe56 and cdde935
