### ISSUE TITLE
[Bug] mate20修补应用后无法自动安装

### ISSUE THREAD

**Issue by 2083696923** [LSPosed/LSPatch#165]
### Steps to reproduce/复现步骤

修补后安装，可以自动卸载但是无法自动安装，中间弹窗显示安装中，但是等了几分钟都没有成功，我考虑到可能没有给予安装权限，然而在我的手机设置中安装权限列表里面没有lspatch这个应用。

### Expected behaviour/预期行为

自动卸载并自动安装

### Actual behaviour/实际行为

自动卸载后一直显示安装中
![Screenshot_20230123_195718_org lsposed lspatch](https://user-images.githubusercontent.com/54367641/214034360-a0b07876-1ec4-4b36-876d-0eff8dd86220.jpg)

### Xposed Module List/Xposed 模块列表

```Shell
暂时还没有列表
```

### LSPatch version/LSPatch 版本

0.5.1 (360)

### Android version/Android 版本

9 (API 28)

### Shizuku version/Shizuku 版本

12.14.0.r914.e88de6a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-HMA-AL00-HUAWEIHMA-AL00-2023-01-23-20-00-16 (1).zip](https://github.com/LSPosed/LSPatch/files/10479484/bugreport-HMA-AL00-HUAWEIHMA-AL00-2023-01-23-20-00-16.1.zip)

**Comment by myxuguiyuan** [comment]
解决了吗

**Comment by yujincheng08** [comment]
应该。

**Comment by myxuguiyuan** [comment]
怎么解决的呀
