### ISSUE TITLE
`native_init` no be called

### ISSUE THREAD

**Issue by moeshin** [LSPosed/LSPatch#17]
My module can run normally on LSPosed 1.5.1.

According to: https://github.com/LSPosed/LSPosed/wiki/Native-Hook

There are two error logs here:
```text
E/LSPosed: failed to open [anon:linker_alloc]
E/LSPatch: hookApplicationStub
```

**Comment by yujincheng08** [comment]
known issue. will fix

**Comment by Dr-TSNG** [comment]
Fixed by https://github.com/LSPosed/LSPatch/commit/813802d18c31fdae2abf5378b3ce56ca629b66f8
