### ISSUE TITLE
[Bug] cr crash

### ISSUE THREAD

**Issue by redn3ck** [LSPosed/LSPatch#193]
### Steps to reproduce/复现步骤

1. 修补《皇室战争》https://cr.qq.com/zlkdatasys/mct/d/play.shtml?device=android，目前最新版本为 3.3186.4，关键是上个版本的游戏是正常的

### Expected behaviour/预期行为

正常运行

### Actual behaviour/实际行为

安装修补后打开程序，10s左右必定闪退，已测试harmonyOS 3.0.0，安卓12，均稳定复现该bug

### Xposed Module List/Xposed 模块列表

```Shell
未嵌入模块，单纯为了拉取微信登录
```

### LSPatch version/LSPatch 版本

0.5.1(360)，0.5.1(374) 均已测试

### Android version/Android 版本

harmonyOS 3.0.0.208

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

```
API 版本
93

LSPatch 版本
0.5.1 (374)

框架版本
1.8.6 (6712)

系统版本
12 (API 31)

设备
HUAWEI LIO-AN00 

系统架构
arm64-v8a

日志无法copy，截图了

```

![图片](https://github.com/LSPosed/LSPatch/assets/12512242/fa66afdb-c7b0-4a1f-955a-c9e1e583b6fe)

**Comment by Dr-TSNG** [comment]
重打包游戏本来就是作死行为

**Comment by redn3ck** [comment]
万不得已，谁也不想重打包游戏，修补了微信，导致很多程序无法拉起微信登录，请问有解决方案么？
