### ISSUE TITLE
[Feature Request] Remove "QUERY_ALL_PACKAGES" normal permission when embedding

### ISSUE THREAD

**Issue by powerfulsaber** [LSPosed/LSPatch#194]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

There shouldn't be a need to have this permission when the module is embedded into the package.

### Describe the solution you'd like/描述你想要的解决方案

If the user is embedding the module, don't add this permission to the manifest.

**Comment by yujincheng08** [comment]
its not an issue. u hv to access all possible modules. so u hv to hv this permission.

**Comment by yujincheng08** [comment]
oh wait. embedding mode now does not support external modules, right? @Dr-TSNG so looks like it needs to be solved.
