### ISSUE TITLE
[Bug] Corrupted zip header

### ISSUE THREAD

**Issue by srdr0p** [LSPosed/LSPatch#196]
### Steps to reproduce/复现步骤

1.  Download apk (Baidu Tieba12.41.1.1 ) from 
    https://downapp.baidu.com/baidutieba/AndroidPhone/12.40.1.1.64/1/1019960a/20230506170552/baidutieba_AndroidPhone_12-40-1-1-64_1019960a.apk
2. Use  [APKEditor]{https://github.com/REAndroid/APKEditor/} to refactor
    ```
    java -jar APKEditor-1.2.1.jar x -i baidutieba_AndroidPhone_1019960a.apk
    ```
3. Use LSPatch
    ```
    java -jar jar-v0.5.1-375-debug.jar baidutieba_AndroidPhone_1019960a_refactored.apk
    ```
4. Use zipalgin / WinRar / 7-zip to view the apk  output in Step 3

### Expected behaviour/预期行为

No error reported

### Actual behaviour/实际行为

Error reported. Such as reported by zipalgin:
> zip W 05-22 16:22:56 11044  3332 WARNING: header mismatch

### Xposed Module List/Xposed 模块列表

```Shell
N/A
```

### LSPatch version/LSPatch 版本

0.5.1-375

### Android version/Android 版本

N/A

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Apk file/Apk 文件

N/A

### Logs/日志

Parsing original apk...
Register apk signer with default keystore...
Original signature
3082024b308201b4a00302010202044ea543e4300d06092a864886f70d01010505003069310e300c060355040613053130303030311e301c06035504080c15e4b8ade58d8ee4babae6b091e585b1e5928ce59bbd310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e799bee5baa631153013060355040b0c0ce799bee5baa6e8b4b4e590a73020170d3131313032343130353432385a180f33303131303232343130353432385a3069310e300c060355040613053130303030311e301c06035504080c15e4b8ade58d8ee4babae6b091e585b1e5928ce59bbd310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e799bee5baa631153013060355040b0c0ce799bee5baa6e8b4b4e590a730819f300d06092a864886f70d010101050003818d0030818902818100b17c8a1a350a202f33e461293638cbf1b6bd481877a87379cd6b99d2ec33aa123d9e16028e94c89a3ea268bd5b055869cd99bf10780e7fafa6254a4471d4d57d36589331e28f66b0044bd8e6cc0cd82dc4fa21f28887776b2094118f859739e8271811894260d9a8f36482fc4e2e9df40dc953e2c2da429ea1101524bce33fd10203010001300d06092a864886f70d010105050003818100026d1e8e8d60a36583224e9bf98398528d6b1ca79ef0982849581b1c8736dc02610ae0e0bfad1b6499a11ac09df08eb46978a97058d9cc712536232b7b1a1e567b70fc2d3bb1958e08da7f87225d4ea1b04a96718031d745f84c48bdac656906d7f51bba8adbaa9187ba095e5335bd89f978c3f1f6f07351af18a56cf4ec1360
original appComponentFactory class: com.baidu.nps.hook.component.NPSComponentFactory
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
Creating nested apk link...
Writing apk...
Done. Output APK: .\baidutieba_AndroidPhone_1019960a_refactored-360-lspatched.apk

**Comment by yujincheng08** [comment]
i think this is expected if the apk can be installed correctly. we use some zip magic to reduce the apk size.
