### ISSUE TITLE
[Feature Request] 增强去除签名校验

### ISSUE THREAD

**Issue by suqiernb** [LSPosed/LSPatch#207]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

有些程序会在内部自己实现的 `openat` 函数, 我们可以使用 `seccomp` 重定向 `__NR_openat` 去除签名校验

### Describe the solution you'd like/描述你想要的解决方案

增强去除签名校验, 绕过二次打包检查

**Comment by Dr-TSNG** [comment]
我们不会做类似功能，至少不会作为开源实现。
