### ISSUE TITLE
[Feature Request] 在 hook 环境下获取模块 apk 内的 assets

### ISSUE THREAD

**Issue by jiwangyihao** [LSPosed/LSPatch#217]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

之前我在 https://github.com/LSPosed/LSPatch/issues/159 中希望提供预配置功能， @vvb2060 大佬在 https://github.com/LSPosed/LSPatch/issues/159#issuecomment-1529108033 中提到可以让用户修改 assets 中的文件实现配置效果。

现在想来大佬的意思应该是修改修补后的宿主 apk 中的 assets，可是这样就会带来签名上的麻烦（二改后的安装包签名将与 LSPatch 直接修改的不同），同时作为一个通用模块，在批量修补的时候挨个配置也十分低效。

我自己的想法是希望用户能够直接修改模块的 apk 来完成配置（同时解决了上面的两个问题），可这样带来的新问题就是……似乎没有办法在 hook 环境中获取模块自身的 assets。

我本来想或许可以先从宿主的 assets 中获取模块的 apk 然后再拆包获取文件，但 `assetManager` 似乎不能请求到 `lspatch` 里的文件（`open` 具体文件会提示 `FileNotFound`，`list` 则看不到 `lspatch` 这个文件夹），个人猜想也许是屏蔽了相关请求（来隐藏 LSPatch 本身？）

### Describe the solution you'd like/描述你想要的解决方案

希望能提供在 hook 环境中获取模块 apk 内的 assets 的方法

**Comment by yujincheng08** [comment]
apk 路径都有了，直接自己解压一下不行吗？

**Comment by jiwangyihao** [comment]
> apk 路径都有了，直接自己解压一下不行吗？

你说模块的apk路径吗，这个在hook宿主的时候从宿主的assetsManager里直接获取模块的apk是获取不到的诶（上面有说）

**Comment by yujincheng08** [comment]
那就不要用 assetsManager 啊

**Comment by jiwangyihao** [comment]
> 那就不要用 assetsManager 啊

啊（那用什么😂
（抱歉，安卓开发不是很熟）

**Comment by yujincheng08** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipInputStream.html

**Comment by jiwangyihao** [comment]
> https://docs.oracle.com/javase/8/docs/api/java/util/zip/ZipInputStream.html

这个解压的我知道啊，你是说直接解压宿主apk的意思吗？
（我看其他的issue里面不是也有在讨论对宿主apk路径的重定向，之后请求宿主的apk不会出现拿不到原包的情况吗）

**Comment by yujincheng08** [comment]
解压模块apk

**Comment by yujincheng08** [comment]
https://api.xposed.info/reference/de/robv/android/xposed/IXposedHookZygoteInit.StartupParam.html#modulePath

**Comment by jiwangyihao** [comment]
> https://api.xposed.info/reference/de/robv/android/xposed/IXposedHookZygoteInit.StartupParam.html#modulePath

我研究一下😂
谢谢大佬
