### ISSUE TITLE
[Bug] GBoard unable to be patched, signature verification still fails

### ISSUE THREAD

**Issue by null-von-sushi** [LSPosed/LSPatch#218]
### Steps to reproduce/复现步骤

1. Download gboard [like this version here](https://www.apkmirror.com/apk/google-inc/gboard/gboard-12-2-03-469624536-release/gboard-the-google-keyboard-12-2-03-469624536-beta-arm64-v8a-2-android-apk-download/)
2. Try to patch it as "portable", select a module such as [this one](https://forum.xda-developers.com/t/mod-xposed-nsfw-gboard.3522308/post-88167837)
3. Select any of the signature bypass options. I tried all 3.
4. Start patching, then install the file.
5. Try to run the app. It will crash without starting.

### Expected behaviour/预期行为

Signature bypass should also work on GBoard, the app should open without crashing due to a signature error.

### Actual behaviour/实际行为

~~After trying to open the app, somehow get to the LSPatcher-generated crash log (I am really sorry, but I was unable to figure out how to get the log to shown up). ~~
Check the Android System UI error generated for Gboard
The error will be an illegal java exception: `APK is signed by unrecognized certificates: C081890CF2A1ADF13E56D7B50A4F3D8EDB35B7C46D6CCC732DD997B7E433BE1D`
![Screenshot_20230710-124907](https://github.com/LSPosed/LSPatch/assets/13616397/9e89a258-1ebd-4197-bdf2-23af2f74f708)

### Xposed Module List/Xposed 模块列表

```Shell
com.imadev.nsfw 1.4.4
```

### LSPatch version/LSPatch 版本

LSPatch Version
0.5.1 (382)
Framework Version
1.8.6 (6911)

### Android version/Android 版本

13 (API 33)

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
Launch patch
Processing /data/user/0/org.lsposed.lspatch/cache/apk/com.google.android.inputmethod.latin_12.2.03.469624536-beta-arm64-v8a-94563614_minAPI23(arm64-v8a)(nodpi)_apkmirror.com.apk -> /data/user/0/org.lsposed.lspatch/cache/apk/com.google.android.inputmethod.latin_12.2.03.469624536-beta-arm64-v8a-94563614_minAPI23(arm64-v8a)(nodpi)_apkmirror.com-382-lspatched.apk
apk path: /data/user/0/org.lsposed.lspatch/cache/apk/com.google.android.inputmethod.latin_12.2.03.469624536-beta-arm64-v8a-94563614_minAPI23(arm64-v8a)(nodpi)_apkmirror.com.apk
Parsing original apk...
Register apk signer with default keystore...
Original signature
308204433082032ba003020102020900c2e08746644a308d300d06092a864886f70d01010405003074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964301e170d3038303832313233313333345a170d3336303130373233313333345a3074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f696430820120300d06092a864886f70d01010105000382010d00308201080282010100ab562e00d83ba208ae0a966f124e29da11f2ab56d08f58e2cca91303e9b754d372f640a71b1dcb130967624e4656a7776a92193db2e5bfb724a91e77188b0e6a47a43b33d9609b77183145ccdf7b2e586674c9e1565b1f4c6a5955bff251a63dabf9c55c27222252e875e4f8154a645f897168c0b1bfc612eabf785769bb34aa7984dc7e2ea2764cae8307d8c17154d7ee5f64a51a44a602c249054157dc02cd5f5c0e55fbef8519fbe327f0b1511692c5a06f19d18385f5c4dbc2d6b93f68cc2979c70e18ab93866b3bd5db8999552a0e3b4c99df58fb918bedc182ba35e003c1b4b10dd244a8ee24fffd333872ab5221985edab0fc0d0b145b6aa192858e79020103a381d93081d6301d0603551d0e04160414c77d8cc2211756259a7fd382df6be398e4d786a53081a60603551d2304819e30819b8014c77d8cc2211756259a7fd382df6be398e4d786a5a178a4763074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964820900c2e08746644a308d300c0603551d13040530030101ff300d06092a864886f70d010104050003820101006dd252ceef85302c360aaace939bcff2cca904bb5d7a1661f8ae46b2994204d0ff4a68c7ed1a531ec4595a623ce60763b167297a7ae35712c407f208f0cb109429124d7b106219c084ca3eb3f9ad5fb871ef92269a8be28bf16d44c8d9a08e6cb2f005bb3fe2cb96447e868e731076ad45b33f6009ea19c161e62641aa99271dfd5228c5c587875ddb7f452758d661f6cc0cccb7352e424cc4365c523532f7325137593c4ae341f4db41edda0d0b1071a7c440f0fe9ea01cb627ca674369d084bd2fd911ff06cdbf2cfa10dc0f893ae35762919048c7efc64c7144178342f70581c9de573af55b390dd7fdb9418631895d5f759f30112687ff621410c069308a
original appComponentFactory class: null
original minSdkVersion: 23
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/liblspatch.so
added assets/lspatch/so/x86/liblspatch.so
added assets/lspatch/so/armeabi-v7a/liblspatch.so
added assets/lspatch/so/arm64-v8a/liblspatch.so
Embedding modules...
  - com.imadev.nsfw
Creating nested apk link...
Writing apk...
Done. Output APK: /data/user/0/org.lsposed.lspatch/cache/apk/com.google.android.inputmethod.latin_12.2.03.469624536-beta-arm64-v8a-94563614_minAPI23(arm64-v8a)(nodpi)_apkmirror.com-382-lspatched.apk
Patched files are saved to primary:LSpatch
```
</details>

**Comment by null-von-sushi** [comment]
Full error from system UI for Gboard
<details>
```
```
type: crash
osVersion: google/raven/raven:13/TQ3A.230605.012/2023061402:user/release-keys
package: com.google.android.inputmethod.latin:94563614
process: com.google.android.inputmethod.latin
processUptime: 688 + 303 ms

java.lang.RuntimeException: Unable to create application com.google.android.apps.inputmethod.latin.ImeLatinApp: java.lang.IllegalStateException: APK is signed by unrecognized certificates: C081890CF2A1ADF13E56D7B50A4F3D8EDB35B7C46D6CCC732DD997B7E433BE1D
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6829)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalStateException: APK is signed by unrecognized certificates: C081890CF2A1ADF13E56D7B50A4F3D8EDB35B7C46D6CCC732DD997B7E433BE1D
	at bpb.c(PG:77)
	at com.google.android.apps.inputmethod.latin.ImeLatinApp.c(PG:1)
	at com.google.android.apps.inputmethod.libs.framework.core.AppBase.onCreate(PG:249)
	at bos.onCreate(PG:2)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1282)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6824)
	... 11 more

```
```
</details>

**Comment by JasonKhew96** [comment]
unable to reproduce in `v0.5.1-392` with lv1 and lv2 signature bypass
