### ISSUE TITLE
[Feature Request] 通过调用 Dhizuku 相关 API 以安装应用

### ISSUE THREAD

**Issue by MSDNicrosoft** [LSPosed/LSPatch#219]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

无

### Describe the solution you'd like/描述你想要的解决方案

如题，而不是仅仅局限于只能使用 Shizuku。

Dhizuku 是通过“设备所有者”激活的，对于非 root 用户来说，相较于 Shizuku 运行更稳定（即便是重启设备，也不会停止运行）。

### Additional context/其他信息

Dhizuku：https://github.com/iamr0s/Dhizuku
Dhizuku API：https://github.com/iamr0s/Dhizuku-API

**Comment by vvb2060** [comment]
以后要跑daemon的，设备拥有者没这个权限，现在只用于安装apk是因为拆分包安装困难，先做了这个功能。
