### ISSUE TITLE
[Feature Request] Lspatch module working in Lsposed

### ISSUE THREAD

**Issue by privacyguy123** [LSPosed/LSPatch#239]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Is it possible to have Lsposed and Lspatch installed at the same time? 

I notice that module AllTrans designed for Lspatch does not work properly in Lsposed. 

### Describe the solution you'd like/描述你想要的解决方案

Is there documentation out there to outline how to make Lspatch modules work properly under Lsposed?

**Comment by yujincheng08** [comment]
No possible.
