### ISSUE TITLE
[Bug] Lspatch unable to match signature 

### ISSUE THREAD

**Issue by crabby605** [LSPosed/LSPatch#241]
### Steps to reproduce/复现步骤

1. Open the app
1. Click on add
1. Add the module 
Patch the module
An error after installation 

### Expected behaviour/预期行为

The app should embed the module for Snapchat and install the patched apk

### Actual behaviour/实际行为

Unable to match the signatures 

### Xposed Module List/Xposed 模块列表

```Shell
Snapenhance
```

### LSPatch version/LSPatch 版本

0.5.1

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

13.5

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```

```
</details>

**Comment by yujincheng08** [comment]
u hv to uninstall the original app
