### ISSUE TITLE
[Bug] INSTALL_FAILED_USER_RESTRICTED: Install canceled by user

### ISSUE THREAD

**Issue by ZeyMax** [LSPosed/LSPatch#243]
### Steps to reproduce/复现步骤

1. I select Snapchat to patch 
2. I click on portable and add Snap Enhancer
3. I click install so it uninstall and reinstall the new app patched
4. I get this error and the app didn't installed : INSTALL_FAILED_USER_RESTRICTED: Install canceled by user

### Expected behaviour/预期行为

it should reinstall the app patched 

### Actual behaviour/实际行为

it can't install the app

### Xposed Module List/Xposed 模块列表

```Shell
Snap enhancer
```

### LSPatch version/LSPatch 版本

0.5.1

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

13.5 

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Apk file/Apk 文件

.

### Logs/日志

sorry but idk how to put the log

**Comment by yujincheng08** [comment]
Not our issue.
