### ISSUE TITLE
[Bug] Xiaomi 13 update based on android14 MIUI14.0.3 UMBCNXM, Lspatch startup flash back

### ISSUE THREAD

**Issue by kingsunsun2012** [LSPosed/LSPatch#250]
### Steps to reproduce/复现步骤

1. 启动Lspatch出现闪退
2.微心微X模块启动“提示lspatch卡死”

### Expected behaviour/预期行为

lspatch正常启动，各模块正常使用

### Actual behaviour/实际行为

Lspatch 无法正常启动，出现闪退，模块提示”Lspatch“出现卡死

### Xposed Module List/Xposed 模块列表

```Shell
微信X
QAuxiliary
抖音小能手
等等。。
```

### LSPatch version/LSPatch 版本

Lspatch-v0.5.1-390

### Android version/Android 版本

Xiaomi 13 update based on android14 MIUI14.0.3 UMBCNXM

### Shizuku version/Shizuku 版本

Shizuku13.5

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
已提供使用问题日志压缩包
[小米13_Lspatch启动闪退_mut_2023-10-23_21-32-57_logcat.zip](https://github.com
[小米13_Lspatch启动闪退_mut_2023-10-23_21-32-57_logcat.zip](https://github.com/LSPosed/LSPatch/files/13071368/13_Lspatch._mut_2023-10-23_21-32-57_logcat.zip)
/LSPosed/LSPatch/files/13071299/13_Lspatch._mut_2023-10-23_21-32-57_logcat.zip)

```
</details>

**Comment by JasonKhew96** [comment]
logs missing
