### ISSUE TITLE
[Feature Request]需要更新

### ISSUE THREAD

**Issue by CharWhyChar** [LSPosed/LSPatch#265]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

目前框架版本6649打包的apk在安卓13/14有bug，需要将内置框架版本更新至lsposed7041以上。

### Describe the solution you'd like/描述你想要的解决方案

lsposed近期进行了大量更新，希望lspatch能同步版本。

**Comment by Howard20181** [comment]
b0fbc7341c7ef4d177cb12cbd3cecb463c62e988
