### ISSUE TITLE
[Bug] App patched by manager can't load module randomly (local mode, 本地模式)

### ISSUE THREAD

**Issue by dev-techmoe** [LSPosed/LSPatch#266]
### Steps to reproduce/复现步骤

OS: MIUI 14.0.25 (Based on Android 13) non-rooted

1. Download Bilibili APP 7.50.0 [wandoujia link](https://www.wandoujia.com/apps/281291/history_v7500300)
2. Download and install latest LSPatch manager (0.5.1), and enable Shizuku
3. Patch Bilibili app using local mode (本地模式)
4. Install apk
5. Go to MIUI system setting and find out LSPatch app, enable the auto-startup permission and set battery-save mode to unlimited

### Expected behaviour/预期行为

APP and module working normally

### Actual behaviour/实际行为

Module can load randomly (kill patched bilibili app and reopen more times, BiliRoaming module can't be loaded sometimes) and no any notification or logs.

### Xposed Module List/Xposed 模块列表

```Shell
https://github.com/yujincheng08/BiliRoaming/releases/tag/v1.7.0 v1.7.0
```

### LSPatch version/LSPatch 版本

0.5.1

### Android version/Android 版本

Android 13 (MIUI 14.0.25) non-rooted

### Shizuku version/Shizuku 版本

13.5, adb mode

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by Howard20181** [comment]
![Screenshot_2023-11-23-16-01-46-279_com.miui.securitycenter-edit.jpg](https://github.com/LSPosed/LSPatch/assets/40033067/d279a76d-d53a-4802-8c85-230be9d383ad)

**Comment by dev-techmoe** [comment]
> ![Screenshot_2023-11-23-16-01-46-279_com.miui.securitycenter-edit.jpg](https://user-images.githubusercontent.com/40033067/285130721-d279a76d-d53a-4802-8c85-230be9d383ad.jpg)

给这个权限之后测试了一下问题依旧，复现非常稳定

**Comment by Howard20181** [comment]
> > ![Screenshot_2023-11-23-16-01-46-279_com.miui.securitycenter-edit.jpg](https://user-images.githubusercontent.com/40033067/285130721-d279a76d-d53a-4802-8c85-230be9d383ad.jpg)
> 
> 给这个权限之后测试了一下问题依旧，复现非常稳定

用 `adb logcat` 获取日志发一下

**Comment by dev-techmoe** [comment]
```plain
# logcat | grep 25958 | tee lsposed.log
11-23 17:24:36.453 21148 21148 E LSPosed : java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.lsposed.lspd.core.ApplicationServiceClient.getModulesList()' on a null object reference
11-23 17:24:36.453 21148 21148 E LSPosed : 	at org.lsposed.lspd.core.Startup.bootstrapXposed(Startup.java:68)
11-23 17:24:36.453 21148 21148 E LSPosed : 	at org.lsposed.lspatch.loader.LSPApplication.onLoad(LSPApplication.java:90)
11-23 17:24:36.453 21148 21148 E LSPosed : 	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:370)
11-23 17:24:37.044 21148 21191 E LSPosed : java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder org.lsposed.lspd.core.ApplicationServiceClient.requestModuleBinder(java.lang.String)' on a null object reference
11-23 17:24:37.044 21148 21191 E LSPosed : 	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.afterHookedMethod(LoadedApkGetCLHooker.java:90)
11-23 17:24:37.380 21148 21380 E LSPosed : java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder org.lsposed.lspd.core.ApplicationServiceClient.requestModuleBinder(java.lang.String)' on a null object reference
11-23 17:24:37.380 21148 21380 E LSPosed : 	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.afterHookedMethod(LoadedApkGetCLHooker.java:90)
11-23 17:24:37.390 21148 21380 E LSPosed : java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.IBinder org.lsposed.lspd.core.ApplicationServiceClient.requestModuleBinder(java.lang.String)' on a null object reference
11-23 17:24:37.390 21148 21380 E LSPosed : 	at org.lsposed.lspd.hooker.LoadedApkGetCLHooker.afterHookedMethod(LoadedApkGetCLHooker.java:90)
11-23 17:24:40.297 21659 21659 E LSPosed : java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.lsposed.lspd.core.ApplicationServiceClient.getModulesList()' on a null object reference
11-23 17:24:40.297 21659 21659 E LSPosed : 	at org.lsposed.lspd.core.Startup.bootstrapXposed(Startup.java:68)
11-23 17:24:40.297 21659 21659 E LSPosed : 	at org.lsposed.lspatch.loader.LSPApplication.onLoad(LSPApplication.java:90)
11-23 17:24:40.297 21659 21659 E LSPosed : 	at org.lsposed.lspatch.metaloader.LSPAppComponentFactoryStub.<clinit>(Unknown Source:370)
```

启动bilibili时一直在报这个，如果需要全部日志我得晚些时候再提供 @Howard20181

**Comment by Howard20181** [comment]
这个时候管理器确定在后台运行吗？

**Comment by dev-techmoe** [comment]
> 这个时候管理器确定在后台运行吗？

我觉得只要MIUI不犯病应该是在的。

- MIUI的省电目前已经改成无限制了，自启动权限也给了
- 最近任务中没有划掉
- 在运行bilibili之前，在应用详情中确认了LSPatch运行状态为正在运行

**Comment by Howard20181** [comment]
不对旧版本提供支持
