### ISSUE TITLE
[Bug]  multi user apk failed

### ISSUE THREAD

**Issue by zinhuofc** [LSPosed/LSPatch#270]
### Steps to reproduce/复现步骤

Create a patched APK in the second space and install it, then open it

### Expected behaviour/预期行为

work

### Actual behaviour/实际行为

when opening a fixed app in the second space of android, it does not open and when copying error information it appears install_failed_version_downgrade: downgrade detected: Update version code 1 is older than current 44

Note I don't have a copy installed

### Xposed Module List/Xposed 模块列表

```Shell
no
```

### LSPatch version/LSPatch 版本

latest

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

latest

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

<details>

```
# Replace this line with the log / 将此行用日志替换
```
</details>

**Comment by vvb2060** [comment]
no multi, only one apk

**Comment by zinhuofc** [comment]
> sem multi, apenas um apk

Did you mean to post the apk?

**Comment by zinhuofc** [comment]
> no multi, only one apk

I want to collaborate with the project help guy
My favorite app is only working on lspatch, but not on multi-user with newer versions
