### ISSUE TITLE
[Bug] QQ crashed on android10 在安卓10上QQ闪退

### ISSUE THREAD

**Issue by mikomikosuika** [LSPosed/LSPatch#276]
### Steps to reproduce/复现步骤

1.修补QQ8.9.93安装包，加载qauxiliary和tsbattery模块，安装修补后的安装包并使用，发现闪退情况
2.尝试分别使用本地模式和集成模式，闪退情况相同
3.闪退后尝试只使用其中一个模块，发现仍旧闪退
4.取消所有模块时应用能正常启动，再次勾选模块之后依旧闪退
5.修补后的安装包传到另一个安卓11的手机上能够正常使用，仅在这个安卓10的手机上闪退

### Expected behaviour/预期行为

应用正常启动

### Actual behaviour/实际行为

1. 加载tsbattery模块时，第一次启动正常并且能打开模块设置，第二次启动之后打开模块设置就黑屏，之后一直闪退，再也无法启动
2. 加载qauxiliary模块时，一开始概率闪退，重启几次之后能用，一段时间后变为一直闪退，再也无法启动
3. 闪退并非瞬间闪退，而是启动进入QQ主界面之后几秒钟后才闪退，且在这几秒钟内暂时可以正常操作

### Xposed Module List/Xposed 模块列表

```Shell
tsbattery
qauxiliary
```

### LSPatch version/LSPatch 版本

0.6（398）

### Android version/Android 版本

10（EMUI10.1）

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

> 修补应用时的日志

Launch patch
Processing/data/user/0/
org.lsposed.lspatch/cache/apk/
Android_8.9.93_64.apk->/data/user/0/
org.lsposed.lspatch/cache/apk/
Android_8.9.93_64-398-lspatched.apk
apk path:/data/user/0/
org.lsposed.lspatch/cache/apk/
Android_8.9.93_64.apk
Parsing original apk...
Register apk signer with default
keystore...
Original signature
30820253308201bca00302010202044bbb0361300d06092a864886f70d0101050500306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b30090603550403130251513020170d3130303430363039343831375a180f32323834303132303039343831375a306d310e300c060355040613054368696e61310f300d06035504080c06e58c97e4baac310f300d06035504070c06e58c97e4baac310f300d060355040a0c06e885bee8aeaf311b3019060355040b0c12e697a0e7babfe4b89ae58aa1e7b3bbe7bb9f310b300906035504031302515130819f300d06092a864886f70d010101050003818d0030818902818100a15e9756216f694c5915e0b529095254367c4e64faeff07ae13488d946615a58ddc31a415f717d019edc6d30b9603d3e2a7b3de0ab7e0cf52dfee39373bc472fa997027d798d59f81d525a69ecf156e885fd1e2790924386b2230cc90e3b7adc95603ddcf4c40bdc72f22db0f216a99c371d3bf89cba6578c60699e8a0d536950203010001300d06092a864886f70d01010505000381810094a9b80e80691645dd42d6611775a855f71bcd4d77cb60a8e29404035a5e00b21bcc5d4a562482126bd91b6b0e50709377ceb9ef8c2efd12cc8b16afd9a159f350bb270b14204ff065d843832720702e28b41491fbc3a205f5f2f42526d67f17614d8a974de6487b2c866efede3b4e49a0f916baa3c1336fd2ee1b1629652049
original appComponentFactory class:androidx.core.app.CoreComponentFact ory
original minSdkVersion:23
Patching apk...
Adding config...
Adding metaloader dex...
Adding loader dex...
Adding native lib...
added assets/lspatch/so/x86_64/
liblspatch.so
added assets/lspatch/so/x86/
liblspatch.so
added assets/lspatch/so/armeabi-v7a/
liblspatch.so
added assets/lspatch/so/arm64-v8a/
liblspatch.so
Embedding modules...
-com.fankes.tsbattery
-io.github.qauxv
Creating nested apk link...
Writing apk...
Done.Output APK:/data/user/0/
org.lsposed.lspatch/cache/apk/
Android_8.9.93_64-398-lspatched.apk
Patched files are saved to
primary:Download

> 系统设置开发者选项里生成的日志

[bugreport-ELS-AN00-HUAWEIELS-AN00-2023-12-10-01-35-38.zip](https://github.com/LSPosed/LSPatch/files/13625174/bugreport-ELS-AN00-HUAWEIELS-AN00-2023-12-10-01-35-38.zip)

**Comment by yujincheng08** [comment]
这个是基于 Android 10 的 EMUI 特有的一个 bug，本来 AOSP 也有，并且修复了，但是华为没有合并 AOSP 的这个修复，所以我们也没办法。

**Comment by mikomikosuika** [comment]
> 这个是基于 Android 10 的 EMUI 特有的一个 bug，本来 AOSP 也有，并且修复了，但是华为没有合并 AOSP 的这个修复，所以我们也没办法。

但是太极能够正常使用，不知道太极是怎么做到的

**Comment by yujincheng08** [comment]
原理都不一样，它的原理不触发这个 bug 呗。

**Comment by yujincheng08** [comment]
https://android-review.googlesource.com/c/platform/art/+/1149193

这个就是 bug 的修复。别纠结了。
