### ISSUE TITLE
[Bug] vivo rom读取应用列表相关问题

### ISSUE THREAD

**Issue by HoratioShaw** [LSPosed/LSPatch#277]
### Steps to reproduce/复现步骤

1. 升级到0.6 (399)
2.软件内提示无已修补应用
3.在权限管理器内显示已禁止读取应用列表（在之前的版本或手动授予权限可正常显示）
![Screenshot_20231210_171945](https://github.com/LSPosed/LSPatch/assets/72498396/d317474f-c687-4ede-99ea-8db18daefcb0)

### Expected behaviour/预期行为

弹出“读取应用列表”权限申请

### Actual behaviour/实际行为

不会弹出权限申请，默认拒绝

### Xposed Module List/Xposed 模块列表

```Shell
该问题和模块无关
```

### LSPatch version/LSPatch 版本

7024

### Android version/Android 版本

13

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无

**Comment by HoratioShaw** [comment]
还有一个bug是该版本使用本地模式以后也会有一个更新加载器按钮，按了更新以后也还在

**Comment by vvb2060** [comment]
其它应用，比如clash，mt管理器能正常显示列表吗？

**Comment by HoratioShaw** [comment]
> 其它应用，比如clash，mt管理器能正常显示列表吗？

啊？，，mt管理器会显示授权窗口，允许以后可以显示
![Screenshot_20231210_175237](https://github.com/LSPosed/LSPatch/assets/72498396/3236b0db-a86a-498a-b826-977240fbb185)
lspatch不会显示这个权限授予申请

**Comment by JasonKhew96** [comment]
> 还有一个bug是该版本使用本地模式以后也会有一个更新加载器按钮，按了更新以后也还在

@HoratioShaw 这个逻辑没改过，你用的 debug 版？

**Comment by HoratioShaw** [comment]
> > 还有一个bug是该版本使用本地模式以后也会有一个更新加载器按钮，按了更新以后也还在
> 
> @HoratioShaw 这个逻辑没改过，你用的 debug 版？

~~确实是debug的问题，没注意到~~
