### ISSUE TITLE
不支持接口IXposedHookInitPackageResources吗？

### ISSUE THREAD

**Issue by tpnet** [LSPosed/LSPatch#33]
因为需要注入资源到目标app，入口实现了`IXposedHookZygoteIni`和`IXposedHookInitPackageResources`这两个接口，但是发现打包完之后`handleInitPackageResources`没有回调，initZygote是有回调的。 请问是不支持IXposedHookInitPackageResources吗？

ps： LSPosed是正常的，两个接口都有回调。

**Comment by yujincheng08** [comment]
支持

**Comment by tpnet** [comment]
@yujincheng08  大佬，handleInitPackageResources我这边一直没有回调，为此我做了一个简单的demo，https://github.com/tpnet/TestLspatch，使用的https://github.com/LSPosed/LSPatch/actions/runs/1408508539 这个最新的LSPatch的jar包去打包app和模块的，可以麻烦大佬指导一下是什么问题吗？

**Comment by yujincheng08** [comment]
打开 resource hook 的开关了吗？
https://github.com/LSPosed/LSPatch/blob/36f058f554389b3c97a2dc0944a9437375cedcff/app/src/main/java/org/lsposed/lspatch/loader/LSPApplication.java#L383

**Comment by yujincheng08** [comment]
升级了一下 core 现在不用手动打开开关了 https://github.com/LSPosed/LSPatch/actions/runs/1554117470

**Comment by tpnet** [comment]
芜湖，起飞，我刚刚down完源码，正在build

**Comment by tpnet** [comment]
@yujincheng08   刚刚`Fix Build`的包报错了，如图：
![image](https://user-images.githubusercontent.com/17380722/145215780-2896c396-e006-47db-a191-49bf9b316bbd.png)

**Comment by yujincheng08** [comment]
没改打包相关的东西啊

**Comment by yujincheng08** [comment]
好像是 jar 里面的 so 都不见了，我看看

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPatch/actions/runs/1554390421 好了
