### ISSUE TITLE
0.3版本编译不成功

### ISSUE THREAD

**Issue by netstu** [LSPosed/LSPatch#48]
新的版本用gradlew或是直接在android studio中，都无法通过编译

**Comment by aawwwfax** [comment]
楼主解决了吗？

$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
Type-safe project accessors is an incubating feature.

> Configure project :appstub
WARNING:The option setting 'android.experimental.enableNewResourceShrinker.preciseShrinking=true' is experimental.
The current default is 'false'.
WARNING:The option setting 'android.enableAppCompileTimeRClass=true' is experimental.
The current default is 'false'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':core:minifyReleaseWithR8'.
> Cannot query the value of this property because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
