### ISSUE TITLE
[BUG] Manager 显示上的bug

### ISSUE THREAD

**Issue by david082321** [LSPosed/LSPatch#73]
复现步骤：
1. 打开 Manager
2. 点击底栏的设置 (其实只要不是中间LSPatch的标签就可以)
3. 点击系统的返回按钮
4. 这时候中间画面变成首页，但是底栏还在设置，怎么点都进不去设置了。只能切换到别的页面，才能再点击。

录屏：https://t.me/c/1188689189/920735

**Comment by Dr-TSNG** [comment]
Fixed at b76ea503dd9dcf8df1f638db37983dff61c2bd90
