### ISSUE TITLE
无法自动更新模块路径缓存信息

### ISSUE THREAD

**Issue by hkcnjd** [LSPosed/LSPatch#76]
每次更新模块或插件后，均会导致所有已生效的模块都失效。
我不得不每次在插件更新后，清除lspatch的所有数据后再次勾选或启用模块才会生效。

**Comment by Dr-TSNG** [comment]
> > Fixed at [2f97e18](https://github.com/LSPosed/LSPatch/commit/2f97e18cfab03a264bf9b14a6842b8402d3a1ac6)
> 
> 感谢大佬回复，我是一个小白，普通用户。不太明白大佬回复的这个是啥意思。 还请麻烦大佬可否解释一下是啥意思啊？ 是已经解决这个问题了，还是这个问题不属于lspatch的而是模块的问题呢？

已修复，等推送

**Comment by hkcnjd** [comment]
好的，感谢大佬。
辛苦了。
