### ISSUE TITLE
QQ进入空间卡顿问题

### ISSUE THREAD

**Issue by jiuban590** [LSPosed/LSPatch#84]
### Steps to reproduce/复现步骤

QQ清除后台，或者在后台呆久了点击空间和查看空间图片或者视频

### Expected behaviour/预期行为

点击空间应该在1秒内进入，点击图片应该1秒内弹出。

### Actual behaviour/实际行为

实际点击空间3-5秒进入并伴随瞬间黑屏，点击图片或者视频暂时无反应，但空间漂浮装扮消失，空间可以滑动没有卡死。3-5后会弹出上次点击的图片或者视频，关闭之后在点击别的图片或者视频表现正常，能瞬间弹出。

### Xposed Module List/Xposed 模块列表

```Shell
模块QAuxiliary和XAutoDaily
```

### LSPatch version/LSPatch 版本

0.3.1(317)   1.8.3(6566)

### Android version/Android 版本

安卓11  vivo origin ocean 2.0

### Shizuku version/Shizuku 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPatch and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

附ADB抓的日志，管理器没找到日志
[QQlog.txt](https://github.com/LSPosed/LSPatch/files/8885975/QQlog.txt)

**Comment by t2157** [comment]
来了
