### ISSUE TITLE
[Feature Request] 希望添加应用间互相调用的支持

### ISSUE THREAD

**Issue by zuimengyaoyue** [LSPosed/LSPatch#88]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

应用之间无法互相调用登录，即使他们都加入到了列表内。比如拼多多无法正常调用微信登录（提示未安装微信）。其他类似lspatch的应用例如应用转生和太极可以把要调用的app（微信）和需要登录的app（拼多多）都加入到列表内来实现互相调用。

经过测试，使用对话框取消模块的模拟签名功能从未经过修改的原版安装包内提取微信和拼多多的官方签名然后模拟可以实现互相调用登录。到这里我猜测应该是某些app在登录调用其他应用时会有签名校验的流程，校验失败就会无法正常调用登录

### Describe the solution you'd like/描述你想要的解决方案

感觉可以把加入里面的app的官方签名信息记录一下，互相调用时返回对应的签名信息。相当于把对话框取消模块的模拟签名功能内置到框架中重做时再植入到app内。太极/应用转生应该就是这样实现的，所以感觉lspatch应该也可以通过类似的方法把这个功能植入到被重做的APP中。希望可以实现，用对话框取消模块内嵌这个模拟功能似乎不是很稳定，实测拼多多可以用微信登录和分享，但唱吧和全民K歌，每次分享内容前要先杀掉微信，再点分享。

### Additional context/其他信息

对话框取消模块界面截图
![IMG_20220628_180247](https://user-images.githubusercontent.com/63761337/176152677-9d342412-34a8-4500-aeda-b6f4de8032c4.jpg)

**Comment by akhilkedia** [comment]
自动翻译的中文写在英文下面。

If this feature is implemented, it will cover many common use cases (login across apps, using payment apps, etc.), and will be extremely helpful! 
Also - Thank you for making an open-source version of non-root xposed!

如果实现此功能，它将涵盖许多常见用例（跨应用程序登录、使用支付应用程序等），并且非常有用！
另外 - 感谢您制作非 root xposed 的开源版本！

**Comment by Dr-TSNG** [comment]
edea4552a210465e03e7fd59607d677561cb8760
