### ISSUE TITLE
[Feature Request] 管理器关联apk文件启动方式

### ISSUE THREAD

**Issue by funnycups** [LSPosed/LSPatch#90]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

否

### Describe the solution you'd like/描述你想要的解决方案

希望可以和太极一样，打开apk文件时可以直接选择管理器进行修补

### Additional context/其他信息

![Screenshot_20220706_170650](https://user-images.githubusercontent.com/105932603/177514318-dfd05817-9f68-4fc2-99e2-9afa5065fb76.jpg)

**Comment by aaa8858520** [comment]
希望增加
