### ISSUE TITLE
[Feature Request] 通过其他附加选项来保持管理器后台进程

### ISSUE THREAD

**Issue by funnycups** [LSPosed/LSPatch#92]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

有些时候，即便已经关闭了管理器的电池优化，并且在任务栏锁定了管理器进程，只要管理器或其他修补过的应用不在前台运行，时间一长管理器进程依然会被杀死。

### Describe the solution you'd like/描述你想要的解决方案

通过一些可选的选项允许用户开启一些附加的保活功能，如在通知栏设置管理器的常驻通知等方式来避免进程被回收。

**Comment by Mubai-meng** [comment]
希望可以利用保活的手段来解决冷启动慢的问题

**Comment by LittleChest** [comment]
同求 本地模式修补的应用在LSPatch被杀死后模块不再生效
已关闭电池优化 允许后台运行 允许自启动 在多任务界面锁定
但还是会被杀死

**Comment by Dr-TSNG** [comment]
c191397dc0f031d5b52a714dc71f98760664036e
